GitHub Integration (push files to github repo directly from ipynb file)
Vevesta/VevestaX pull request #87
Opened 2022-06-03 03:43 UTC by nuuron

2022-06-03 04:54 UTC, Priyanka-Vevesta requested changes

2022-06-03 04:54 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +        ipynb_file_name = self.get_filename()
there is a function that does that...please use its output

2022-06-03 04:54 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +    def git_commit(self, repoName, sourceBranch='main', newBranch=None, commitMessage=None):
git commit will be private function

2022-06-03 04:54 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +    def git_commit(self, repoName, sourceBranch='main', newBranch=None, commitMessage=None):
WHy is source branch required

2022-06-03 04:54 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +        ipynb_file_name = self.get_filename()
this will work for python code too.. i mean py files

2022-06-03 04:54 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +                    commitMessage = 'updated ' + ipynb_file_name
the technique used in the commit function will be used to create the branch name and the message will be commit message

2022-06-03 04:54 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +                if commitMessage is None:
if message is none, the technique used will be the commit message.

2022-06-03 04:57 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +    def git_commit(self, repoName, sourceBranch='main', newBranch=None, commitMessage=None):
git commit will be called from inside commit function

2022-06-03 04:58 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +    def git_commit(self, repoName, sourceBranch='main', newBranch=None, commitMessage=None):
It wont ask for  new branch name as argument, instead use the technique used appended with some 6 random numbers at the end.

2022-06-09 06:27 UTC, Priyanka-Vevesta requested changes

2022-06-09 06:27 UTC, Priyanka-Vevesta commented on requirements.txt
> +PyGithub~=1.55
Please update setup.py too always

2022-06-09 06:27 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
>          # api-endpoint
Please write this inside a private function

2022-06-09 06:27 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +        if sourceBranch is None:
this isnt correct... source branch is master branch on which nothing will be pushed except when it has been specified also by the user as newbranch

2022-06-10 07:04 UTC, Priyanka-Vevesta requested changes

2022-06-10 07:04 UTC, Priyanka-Vevesta commented on vevestaX/vevesta.py
> +                newBranch = sourceBranch
new branch will be techniqueUsed...when source branch is main, then it that case a new branch say XGboost will be created

2022-06-24 05:49 UTC, jahnavisana approved these changes

2022-06-25 13:08 UTC, pavanVevesta approved these changes

2022-06-25 13:08 UTC, merged